### ISSUE TITLE
running in nextjs ?

### ISSUE THREAD

**Issue by ghost** [scttcper/react-adsense#32]
i like to implement adsense in nextjs but so far all tries failed. 
Does this package work with nextjs ssr ? Honestly i am pretty stuck ...

Error: `message: 'adsbygoogle.push() error: All ins elements in the … with class=adsbygoogle already have ads in them.', name: 'TagError', pbr: true, stack: 'TagError: adsbygoogle.push() error: All ins elemen…glesyndication.com/pagead/js/adsbygoogle.js:263:4'`

**Comment by mangrove108** [comment]
ok everything works now with this package, thanks alot !

**Comment by mangrove108** [comment]
ok everything works now with this package, thanks alot !

**Comment by XahidEx** [comment]
Did it work?

**Comment by scttcper** [comment]
You can see nextjs ssr on https://xmplaylist.com/

**Comment by XahidEx** [comment]
> You can see nextjs ssr on https://xmplaylist.com/

Should I use Auto ads? (I know I can use this component in markdown) 
But Auto Ads might work well enough. 
And I have another question. Which script component should I use to optimze the Adsense script? Because It seems heavy. Without it, My site's speed was like 94+. Now It's 50-60 🤐

**Comment by scttcper** [comment]
There's no good answer for any of those 🤷‍♂️  Your lighthouse score is always going to take a huge hit with adsense
