### ISSUE TITLE
Ignore "TagError: adsbygoogle.push() error: No slot size for availableWidth=31"

### ISSUE THREAD

**Issue by victoriaSh** [scttcper/react-adsense#33]
I'm using Swiper.js for react to display a loop of pictures with ads inserted between some slides. 
However, sometimes my page crashes after loading, showing the error message: 
'TagError: adsbygoogle.push() error: No slot size for availableWidth=31'. 
This issue seems to be unpredictable and dependent on the window size and the number of pictures in the slider. Sometimes it happens when I resize the window. 
When I switch off loop mode, everything works fine. I suspect that some of the slides are not rendered properly on page load even if my slides and ads has fixed width:
```
	<AdSense.Google
		client="ca-pub-XXX"
		slot="XXX"
		style={{ width: 300, height: 400 }}
		format=""
	/>
```

Is there any way to ignore this error and prevent the page from crashing?

**Comment by scttcper** [comment]
Can always wrap the component in an error boundary https://www.npmjs.com/package/react-error-boundary

**Comment by scttcper** [comment]
I don't think google will like that the ads are being hidden and shown with js though. That's why you see blogs doing whole page loads for their gallery pages

**Comment by victoriaSh** [comment]
Thank you! I didn't even think about that. It's working as expected.
